"""Load and validate .docdrift/config.yaml in the target project.

See examples/docdrift.config.example.yaml for the expected schema.
"""

import os
import re
from dataclasses import dataclass, field
from pathlib import Path

import yaml

CONFIG_RELATIVE_PATH = Path(".docdrift") / "config.yaml"

_ENV_VAR_PATTERN = re.compile(r"\$\{([A-Z0-9_]+)\}")


@dataclass
class ObsidianConfig:
    """Configuration for Obsidian access; see obsidian/factory.py."""

    access_mode: str  # "local" | "rest_api"
    vault_path: Path | None = None
    rest_api_base_url: str | None = None
    rest_api_key: str | None = None


@dataclass
class GithubDocsConfig:
    """Configuration for Flow 2 (Copilot product docs after a merge)."""

    enabled: bool = False
    assignee: str = "copilot"
    docs_paths: list[str] = field(default_factory=lambda: ["docs/", "README.md"])


@dataclass
class DocdriftConfig:
    """Parsed configuration for a target project."""

    repo_name: str
    api_base_url: str
    model: str
    obsidian: ObsidianConfig
    github_docs: GithubDocsConfig
    playbook_dir: Path | None = None
    ignore: list[str] = field(default_factory=list)


def _resolve_env_placeholders(value: str | None) -> str | None:
    """Replace ${ENV_VAR} in strings with the environment variable's value."""
    if not value:
        return value

    def _replace(match: re.Match) -> str:
        return os.environ.get(match.group(1), "")

    return _ENV_VAR_PATTERN.sub(_replace, value)


def load_config(project_root: Path) -> DocdriftConfig:
    """Load .docdrift/config.yaml from the target project."""
    config_path = project_root / CONFIG_RELATIVE_PATH
    if not config_path.exists():
        raise FileNotFoundError(
            f"No configuration found at {config_path}. "
            "Run `docdrift init` first."
        )

    raw = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}

    obsidian_raw = raw.get("obsidian", {}) or {}
    vault_path_raw = obsidian_raw.get("vault_path")
    obsidian = ObsidianConfig(
        access_mode=obsidian_raw.get("access_mode", "local"),
        vault_path=(
            Path(_resolve_env_placeholders(vault_path_raw)).expanduser()
            if vault_path_raw
            else None
        ),
        rest_api_base_url=_resolve_env_placeholders(obsidian_raw.get("rest_api_base_url")),
        rest_api_key=_resolve_env_placeholders(obsidian_raw.get("rest_api_key")),
    )

    github_docs_raw = raw.get("github_docs", {}) or {}
    github_docs = GithubDocsConfig(
        enabled=github_docs_raw.get("enabled", False),
        assignee=github_docs_raw.get("assignee", "copilot"),
        docs_paths=github_docs_raw.get("docs_paths", ["docs/", "README.md"]),
    )

    playbook_dir_raw = raw.get("playbook_dir")

    return DocdriftConfig(
        repo_name=raw.get("repo_name", project_root.name),
        api_base_url=raw.get("api_base_url", "http://localhost:11434/v1"),
        model=raw.get("model", "qwen2.5-coder:14b"),
        obsidian=obsidian,
        github_docs=github_docs,
        playbook_dir=(project_root / playbook_dir_raw) if playbook_dir_raw else None,
        ignore=raw.get("ignore", []),
    )


# Written as the initial .docdrift/config.yaml by `docdrift init`.
# Double braces escape ${...} so .format() does not interpret it as one of its
# own placeholders.
DEFAULT_CONFIG_TEMPLATE = """\
# Generated by `docdrift init` — see the README for all options.
repo_name: "{repo_name}"

api_base_url: "http://localhost:11434/v1"
model: "qwen2.5-coder:14b"

obsidian:
  access_mode: "local"
  vault_path: "~/ObsidianVault/Projects"
  rest_api_base_url: ""
  rest_api_key: "${{OBSIDIAN_REST_API_KEY}}"

github_docs:
  enabled: false
  assignee: "copilot"
  docs_paths:
    - "docs/"
    - "README.md"

ignore:
  - "tests/"
  - "*.lock"
  - ".docdrift/*"
"""


def write_default_config(project_root: Path) -> Path:
    """Write the default config during `docdrift init` (idempotently)."""
    config_path = project_root / CONFIG_RELATIVE_PATH
    config_path.parent.mkdir(parents=True, exist_ok=True)
    if config_path.exists():
        return config_path

    content = DEFAULT_CONFIG_TEMPLATE.format(repo_name=project_root.name)
    config_path.write_text(content, encoding="utf-8")
    return config_path
